Script started on 2015年03月10日 (週二) 21時14分36秒
]0;F24026014@2015cpp: ~/lab1F24026014@2015cpp:~/lab1$ g++-o [C[1@ [C[C[Clab1_B.script[K[K[K[K[K[K[K lab1)[K_B.c[[[K[Kpp
]0;F24026014@2015cpp: ~/lab1F24026014@2015cpp:~/lab1$ g++ -o lab1_B lab1_B.cpp[Kg++ -o lab1_B lab1_B.cpp[6Pscript lab1.scriptls[Kgit push -u lab1 release[1Pmasterlab1[K-u lab1 masterreleasels[Kscript lab1.scriptg++ -o lab1_B lab1_B.cpp[K./lab_B
bash: ./lab_B: No such file or directory
]0;F24026014@2015cpp: ~/lab1F24026014@2015cpp:~/lab1$ ./lab1_B
Input a number: 
22
11
34
17
52
26
13
40
20
10
5
16
8
4
2
1
]0;F24026014@2015cpp: ~/lab1F24026014@2015cpp:~/lab1$ exit

Script done on 2015年03月10日 (週二) 21時15分51秒
